const CODIGOS_ISO: Record<string, string> = {
  Alemania:                'de',
  'Arabia Saudita':        'sa',
  Argelia:                 'dz',
  Argentina:               'ar',
  Australia:               'au',
  Austria:                 'at',
  'Bosnia y Herzegovina':  'ba',
  Brasil:                  'br',
  'Bélgica':               'be',
  'Cabo Verde':            'cv',
  'Canadá':                'ca',
  Catar:                   'qa',
  Colombia:                'co',
  'Corea del Sur':         'kr',
  'Costa de Marfil':       'ci',
  Croacia:                 'hr',
  Curazao:                 'cw',
  Ecuador:                 'ec',
  Egipto:                  'eg',
  Escocia:                 'gb-sct',
  'España':                'es',
  'Estados Unidos':        'us',
  Francia:                 'fr',
  Ghana:                   'gh',
  'Haití':                 'ht',
  Inglaterra:              'gb-eng',
  Irak:                    'iq',
  'Irán':                  'ir',
  'Japón':                 'jp',
  Jordania:                'jo',
  Marruecos:               'ma',
  'México':                'mx',
  Noruega:                 'no',
  'Nueva Zelanda':         'nz',
  'Panamá':                'pa',
  Paraguay:                'py',
  'Países Bajos':          'nl',
  Portugal:                'pt',
  'RD Congo':              'cd',
  'República Checa':       'cz',
  Senegal:                 'sn',
  'Sudáfrica':             'za',
  Suecia:                  'se',
  Suiza:                   'ch',
  'Turquía':               'tr',
  'Túnez':                 'tn',
  Uruguay:                 'uy',
  'Uzbekistán':            'uz',
}

export function getCodigoISO(equipo: string): string {
  return CODIGOS_ISO[equipo] ?? 'un'
}

export const EQUIPOS_VALIDOS: string[] = Object.keys(CODIGOS_ISO)
